### PR TITLE
EI Population and Function

### PR DESCRIPTION
**Pull request by jongornet14**
I created a EI Population of neurons and converted the script into a
function.  I added another script to show how to use the function.

### CODE REVIEW

**Comment by dlevenstein** [comment]
Excellent, this looks great! I'll get a chance to do a full code review over the weekend.

Congrats on your first pull request ;)

**Comment by dlevenstein** [comment]
I'm going to start looking through this tonight - you mentioned you'd added some things like a raster? Do you want to sync those updates before I start going through the code, or will you just merge them in afterwards?

**Comment by jongornet14** [comment]
I don't know if I'll back soon enough to do an update.  If I do an update,
not much will have changed, it will just be new additions of the output of
the function.

Best,

Jonathan

**Comment by dlevenstein** [comment]
Alright - sounds good.  If there are conflicting changes then you’ll just get some practice working with merging branches in github ;)

**Comment by jongornet14** [comment]
Hey Dan,

Hope you are having a good weekend! Were you able to upload the github code
to the master branch? I was thinking about starting the EI balance or
converting the code to an ode solver.

Best,

Jonathan

**Comment by dlevenstein** [comment]
Hey Jonathan - Sorry I haven’t had a chance… was at a wedding this weekend. Why don’t you start another branch and make a second version of the function using an ode solver. I bet it’s good and will only end up doing some minor improvements in the way of documentation etc. I’ll take care of integrating any edits in the ode version once I’ve gone through it.
See you tomorrow!
Dan

**Comment by dlevenstein** [comment]
Looks good Jonathan!

I added 
-some documentation
-Ability of neurons to be randomly connected with given probability 

Now let's see if we can get it balanced. Need to find a parameter regime in the weights etc where the network shows low-rate asynchronous activity for a range of current input, I_e.
I_e is applied to both E and I cells at the moment, which I think should be OK. This is how I have my E-I-A mean field model set up and it can do balance when feedback inhibition is strong enough, especially if the I cells have a higher threshold but higher gain (see attached figures). We could think about how to translate that into the spiking model with John.


[AdaptingInhibitionStabilized.pdf](https://github.com/dlevenstein/SOSpikingModel/files/1289578/AdaptingInhibitionStabilized.pdf)

[SSEIABistability.pdf](https://github.com/dlevenstein/SOSpikingModel/files/1289579/SSEIABistability.pdf)

**Pull request merged**
